# Generated by Django 5.2.17 on 2026-09-17 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('organizations', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Admitted', 'Admitted'), ('Enrolled', 'Enrolled'), ('Active', 'Active'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Suspended', 'Suspended')], default='Enrolled', max_length=50)),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='academics.academicsession')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='organizations.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='people.person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.program')),
            ],
            options={
                'unique_together': {('person', 'program', 'academic_session')},
            },
        ),
    ]
