# Generated by Django 5.2.17 on 2026-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='guardians', to='people.studentprofile'),
        ),
    ]
