# Generated by Django 5.2.17 on 2026-09-18 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('is_core', models.BooleanField(default=False)),
                ('depends_on', models.JSONField(default=list)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=False)),
                ('settings', models.JSONField(default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moduledefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'module')},
            },
        ),
    ]
